apiVersion: v1
kind: Namespace
metadata:
  name: portofolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haik-porto-deployment
  labels:
    app: portofolio
    type: static
  namespace: portofolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haik-porto
  template:
    metadata:
      labels:
        app: haik-porto
    spec:
      containers:
        - name: haikal-personal-portofolio
          image: ghcr.io/haikalrfadhilahh/haikportofolio:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '2'
              memory: '2048Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: haik-porto-service
  namespace: portofolio
spec:
  type: ClusterIP
  selector:
      app: haik-porto
  ports:
    - port: 3000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haik-porto-ingress
  namespace: portofolio
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haik-porto-service
            port:
              number: 3000